---

- name: Converge
  hosts: all
{%- if cookiecutter.molecule_os_type == 'windows' %}
  {% raw -%}
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_user: "{{ molecule_yml.azure_vm_user_name }}"
    ansible_password: "{{ molecule_yml.azure_vm_user_password }}"
  {%- endraw %}
{%- endif %}
  tasks:
    - name: Include tested role
      include_role:
        name: "{{ cookiecutter.role_name }}"
