---
# This is an example playbook to execute Ansible tests.

#- name: Verify
#  hosts: all
#  gather_facts: false
#  tasks:
#  - name: Example assertion
#    assert:
#      that: true

- name: Verify
  hosts: all
{%- if cookiecutter.molecule_os_type == 'linux' %}
  vars:
    ansible_ssh_extra_args: '-o PubkeyAcceptedKeyTypes=+ssh-rsa'  # Centos6 needs +ssh-rsa
{%- endif %}
{%- if cookiecutter.molecule_os_type == 'windows' %}
  vars:
  {% raw -%}
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    ansible_user: "{{ molecule_yml.azure_vm_user_name }}"
    ansible_password: "{{ molecule_yml.azure_vm_user_password }}"
  {%- endraw %}
{%- endif %}

  tasks:
    - name: "Include test_{{ cookiecutter.role_name }} role"
      include_role:
        name: "test_{{ cookiecutter.role_name }}"
